### ISSUE TITLE
Ambiguous Error Message

### ISSUE THREAD

**Issue by Zman94** [Azure/azure-kusto-python#525] opened 2024-02-26 17:07 UTC
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
async def main():
    client = QueuedIngestClient(kcsb)
    client.close()

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())

...
  File "/app/main.py", line 305, in main
    client.close()
  File "/usr/local/lib/python3.9/site-packages/azure/kusto/ingest/ingest_client.py", line 53, in close
    self._resource_manager.close()
  File "/usr/local/lib/python3.9/site-packages/azure/kusto/ingest/_resource_manager.py", line 75, in close
    self._kusto_client.close()
  File "/usr/local/lib/python3.9/site-packages/azure/kusto/data/client.py", line 87, in close
    self._aad_helper.close()
  File "/usr/local/lib/python3.9/site-packages/azure/kusto/data/security.py", line 97, in close
    self.token_provider.close()
  File "/usr/local/lib/python3.9/site-packages/azure/kusto/data/_token_providers.py", line 405, in close
    raise KustoAsyncUsageError("Can't close async token provider with sync close", self.is_async)
azure.kusto.data.exceptions.KustoAsyncUsageError: Method Can't close async token provider with sync close can't be called from a synchronous client
```
#### Problem description

This message doesn't make sense when read outloud. Further, it seems that an async provider shouldn't be calling the synchronous client's close function

#### If query related, does it happen on other platforms (Kusto Web UI, Kusto Explorer)? 

[this step is to help pin point problems that are only specific to this platform.]

#### Output of ``pip freeze`` 

```
❯ cat app/requirements.txt                
aiohttp==3.9.3
aiosignal==1.3.1
asgiref==3.7.2
attrs==23.2.0
azure-common==1.1.28
azure-core==1.30.0
azure-identity==1.15.0
azure-kusto-data==4.3.1
azure-kusto-ingest==4.3.1
azure-mgmt-core==1.4.0
azure-mgmt-resource==23.0.1
azure-storage-blob==12.19.0
azure-storage-queue==12.9.0
cattrs==23.2.3
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
cryptography==42.0.5
DateTime==5.4
frozenlist==1.4.1
idna==3.6
ijson==3.2.3
importlib-resources==6.1.1
isodate==0.6.1
jsii==1.94.0
msal==1.27.0
msal-extensions==1.1.0
multidict==6.0.5
numpy==1.26.4
packaging==23.2
pandas==2.2.1
portalocker==2.8.2
publication==0.0.3
pyarrow==15.0.0
pycparser==2.21
PyJWT==2.8.0
python-dateutil==2.8.2
pytz==2024.1
PyYAML==6.0.1
requests==2.31.0
six==1.16.0
tenacity==8.2.3
typeguard==2.13.3
typing_extensions==4.10.0
tzdata==2024.1
urllib3==2.2.1
yarl==1.9.4
zope.interface==6.2
```

**Comment by AsafMah** [comment] 2024-02-28 08:04
The issue is about mixing an async auth method in a sync client (as ingest is not async).
How did you create the kcsb object?

**Comment by AsafMah** [comment] 2024-03-10 12:06
Closing - feel free to reply and reopen.

**Closed by AsafMah** 2024-03-10 12:06 UTC
