### ISSUE TITLE
Max retries exceeded with url: /v1/rest/mgmt

### ISSUE THREAD

**Issue by mlhk2007** [Azure/azure-kusto-python#115] opened 2019-02-13 00:12 UTC
It had been working fine till the recent change to use connection pool.

Error:
MaxRetryError: HTTPSConnectionPool(host='xxxx.uksouth.kusto.windows.net', port=443): Max retries exceeded with url: /v1/rest/mgmt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f037fbb1b00>: Failed to establish a new connection: [Errno 111] Connection refused',))

I'm behind corporate proxy, using with_aad_application_key_authentication as authentication.

**Comment by roeap** [comment] 2019-02-13 00:38
Hi Kusto Team and @mlhk2007, 

I am experiencing the same issue, when in the corporate network. It works fine when I am no longer behind the proxy, but I also had never experienced any issues with the proxy before - at least with regards to Kusto :). 

I assumed I had to track down the error internally and see if something with our proxy changed, but as other experience the same behavior as well, maybe there is some way to mitigate this in the library?

Thanks!

**Comment by danield137** [comment] 2019-02-14 13:44
@mlhk2007 and @roeap thank you for reporting this issue 👏 

This is a 🐛 caused by switching libs from **requests** to **urllib3** for connection pooling.
We now moved back to requests, and added proper connection pooling.

Latest version should work. 
If you get a chance to confirm fix, that would be great!

**Comment by roeap** [comment] 2019-02-14 17:15
Thanks, that fixed it! From my side you can close the issue.

**Comment by danield137** [comment] 2019-02-17 07:52
Closing. Feel free to reopen when needed.

**Closed by danield137** 2019-02-17 07:52 UTC
