### ISSUE TITLE
dataframe ingestion not honoring fields

### ISSUE THREAD

**Issue by prashanthmadi** [Azure/azure-kusto-python#170] opened 2019-09-23 16:28 UTC
#### Code Sample, a copy-pastable example if possible

```python

fields = ["Name", "Metric", "Source"]
rows = [["p1", 23, "SDK"], ["p2", 25, "SDK"]]

df = pandas.DataFrame(data=rows, columns=fields)

ingestClient.ingest_from_dataframe(df, ingestion_properties=ingestion_props)

```

Total Sample available at below link

https://gist.github.com/prashanthmadi/738da1cf92f825eedf1451b985cee6e8

#### Problem description

As you can see in below screenshot.. field's haven't matched during ingestion.. and i don't see p1, p2 data instead i see metrics in name field

![image](https://user-images.githubusercontent.com/1486808/65444198-28a2e180-ddf5-11e9-8c30-5bc28772d4af.png)

#### If query related, does it happen on other platforms (Kusto Web UI, Kusto Explorer)? 

[this step is to help pin point problems that are only specific to this platform.]

#### Output of ``pip freeze`` 

azure-kusto-data                   0.0.35
azure-kusto-ingest                 0.0.35

**Comment by ArielYehezkely** [comment] 2019-09-25 08:58
Hi, 

It seems that the table schema does not match the DataFrame's columns.
Please try to create a DataFrame that has a column of "TimeStamp" or create an ingestion mapping to map the given columns into to table columns: 

`.create table TestData ingestion csv mapping "csvMapping" '[{ "Name" : "Name", "Ordinal" : 0},{ "Name" : "Metric", "Ordinal" : 1},{ "Name" : "Source", "Ordinal" : 2}]'`

**Comment by ArielYehezkely** [comment] 2019-10-02 14:34
The sample examples ingestion from DataFrame and it doesn't matter if the columns are explicitly named or have the default RangeIndex (0, 1, 2, …, n) naming. 
The library ingests the DataFrame as a CSV and Kusto doesn't match CSV columns to table columns by their names by design. 
I'm closing this issue - if it's still relevant please open again.

**Closed by ArielYehezkely** 2019-10-02 14:34 UTC

**Comment by LucBerge** [comment] 2024-12-05 12:38
I am also observing the same behaviour. So here is what I have done to abstract it:

1. Get the table schema

```python
client = KustoClient(kcsb)
response = client.execute(database, f".show table {table} schema as json")
df = helpers.dataframe_from_result_table(response.primary_results[0])
schema = json.loads(dict(df['Schema'])[0])['OrderedColumns']
```

2. Build a `default_data` dict with all fields in the correct order
```python
default_data = {}
for column in schema:
    default_data[column['Name']] = None
```

3. When I ingest data I compute the new dict from the default dict and the data
```python
data_to_ingest = {}
data_to_ingest.update(default_data)
data_to_ingest.update(data)
print(data_to_ingest)
```

This way you have a dict containing all the fields in the correct order, set to None or to the specified value
